/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package testCalculator;

public class App {

    public static void main(String[] args) {
        
        GetInput input = new GetInput();
        Validate validator = new Validate();
        Calculator calc = new Calculator();
        
        String equation;

        System.out.print("Please enter an equation: ");
        
        equation = input.getEquation();
        int isValid = validator.hasModifier(equation);
        equation = validator.sanitize(equation);
        
        if(isValid >= 0)
        {
            String[] splitEquation = equation.split("[*/+-]");
            if(splitEquation.length == 2) {
                double result = calc.calculate(Double.parseDouble(splitEquation[0]), Double.parseDouble(splitEquation[1]), isValid);
                System.out.println(result);
            }
            else {
                System.out.println("Something went wrong! \nArray size = " + splitEquation.length );
            }
        }
        else
        {
         System.out.println("Equation provided is not valid1");
        }
    }
}
